import 'dart:ui';
import 'package:flutter/cupertino.dart';

class constants {
  static const primarycolor = Color(0xffF5B111);
  static const whitecolor = Color(0xffE5E5E5);
  static const blackcolor = Color(0xff151621);
  static const facebookcolor = Color(0xff4167B2);
  static const googlecolor = Color(0xffF14436);
  static const purblecolor = Color(0xffF1E9D7);
  static const orange = Color(0xffF2994A);
  static const graycolor = Color(0xff4F4F4F);
  static const String usercollection = "Users";
  static const String pinMareker = "pinMarker";
  static const String Favouritecollection = "Favourite";
  static const String UserFavouritecollection = "UserFavourite";
  static const String IsFavourite = "isFavourite";
  static const String Markerscollection = "Markers";
  static const String MarkersCommentscollection = "MarkersComments";
  static const String placeName = "PlaceName";
  static const String placeRate = "PlaceRate";
  static const String ownerName = "OwnerName";
  static const String PlaceImage = "PlaceImage";
  static const String Question1 = "Question1";
  static const String Age = "Age";
  static const String Gender = "Gender";
  static const String Question2 = "Question2";
  static const String Question3 = "Question3";
  static const String Question4 = "Question4";
  static const String Question5 = "Question5";
  static const String Question6 = "Question6";
  static const String Question7 = "Question7";
  static const String Question8 = "Question8";
  static const String Question9 = "Question9";
  static const String Question10 = "Question10";
  static const String Question11 = "Question11";
  static const String Question12 = "Question12";
  static const String Question13 = "Question13";
  static const String Value4 = "Value4";
  static const String Value5 = "Value5";
  static const String Value6 = "Value6";
  static const String Value7 = "Value7";
  static const String Value8 = "Value8";
  static const String Value9 = "Value9";
  static const String Value10 = "Value10";
  static const String Value11 = "Value11";
  static const String Value12 = "Value12";
  static const String Value13 = "Value13";
  static const String Question14 = "Question14";
  static const String Location = "Location";
  static const String username = "UserName";
  static const String age = "Age";
  static const String kGoogleApiKey = "AIzaSyBxzppCAzieemv4N3YASDGt4NuhYyVS6sI";
  static const String score = "Score";
  static const String uid = "Uid";
  static const String time = "Time";
  static const String backgoungimage = 'images/background.svg';
  static const String icon = 'images/icon.svg';

}
