/// Flutter icons Custo_icons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Custo_icons
///      fonts:
///       - asset: fonts/Custo_icons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Custom_icons {
  Custom_icons._();

  static const _kFontFam = 'custom_icons';
  static const _kFontPkg = null;

  static const IconData explore = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lock = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData profile = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heart = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData coins = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
